### ISSUE TITLE
The details of processed input file

### ISSUE THREAD

**Issue by hygeng** [HKUST-KnowComp/Social-Explorative-Attention-Networks#2]
Since I would like to deploy your model on the new dataset, could you add some notes about how the processed dataset file is constructed? like what each line consists of.     
Besides, how the processed processed_user_relation.json is produced? It seems to be part of the proposed model SEAN, but I did not find the implementation. Thanks!

**Comment by icyxiaowenyi** [comment]
> Since I would like to deploy your model on the new dataset, could you add some notes about how the processed dataset file is constructed? like what each line consists of.
> Besides, how the processed processed_user_relation.json is produced? It seems to be part of the proposed model SEAN, but I did not find the implementation. Thanks!

I have put

**Comment by icyxiaowenyi** [comment]
I have put processed_user_relation.json on github.
